version: '3'

services:
  db:
    build:
      context: ./postgres
    container_name: sf4app_db
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - "5433:5432"
  web:
    image: nginx:latest
    container_name: sf4app_web
    networks:
      default:
        aliases:
          - sf4.app
    ports:
      - "8089:8089"
    volumes:
      - ${PATH_WEB}:/data/www/symfony4App
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build:
      context: ./php
    container_name: sf4app_php
    volumes:
      - ${PATH_WEB}:/data/www/symfony4App
    ports:
      - "9000:9000"
    environment:
      - APP_ENV=${APP_ENV}
    depends_on:
      - db